[ids]
*

[main]
capslock = overload(control, esc)
# Right Alt activates navigation layer
rightalt = layer(nav)

[nav]
# Vim-style arrow keys
j = down
k = up
# h and l removed as it conflicts with Polish l
# Home/End
u = home
p = end
# Delete
backspace = delete
